steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '2-structured-data/app.yaml']
  timeout: '1600s'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/poc-ci-cd/bookshelf','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/poc-ci-cd/bookshelf','.']